default:
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: volunteer_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: volunteer_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: volunteer_production
  pool: 5
  timeout: 5000